app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from app.views import *


app_name = 'app'


urlpatterns = [
    path('',dashboard,name='dashboard'),
    path('admin_dashboard',admin_dashboard,name='admin_dashboard'),
    path('quiz',quiz,name='quiz'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name= "logout"),
    path("category_filter", views.category_filter, name= "category_filter"),
]

quiz/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class GeneralUser(AbstractUser):
	userchoices = (
        (1,'ADMIN'),
        (2,'USER'),
    )
	full_name = models.CharField(max_length=500,null=True,blank=True)
	phone = models.CharField(max_length=50,null=True,blank=True,unique=True)
	usertype = models.IntegerField(default=2,choices=userchoices)

class Category(models.Model):
	category_name = models.CharField(max_length=500)

	def __str__(self):
		return self.category_name

class Quiz(models.Model):
	question = models.CharField(max_length=500)
	option_1 = models.CharField(max_length=500)
	option_2 = models.CharField(max_length=500)
	option_3 = models.CharField(max_length=500)
	option_4 = models.CharField(max_length=500)
	currect_answer = models.CharField(max_length=500)
	category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True,related_name="category")


class Result(models.Model):
	user_id = models.ForeignKey('GeneralUser', on_delete=models.CASCADE, null=True, blank=True,related_name="category")
	category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, blank=True,related_name="category_result")
	score = models.IntegerField()
	correct = models.IntegerField()
	wrong = models.IntegerField()

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = GeneralUser
		fields = ("username", "email","full_name", "phone","password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

app/views.py
from django.shortcuts import render,redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate,logout 
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
	print(request.user.id)
	res = Result.objects.filter(id=request.user.id)
	cat = Category.objects.all()
	return render(request,'dashboard.html',{'res':res,'cat':cat})


def quiz(request):
	wrong=0
	correct=0
	score=0
	questions=Quiz.objects.all()
	category=Category.objects.get(id=request.POST.get('category1'))
	print("------",category)
	for q in questions:
		if request.POST.get(q.question) == q.currect_answer:
			score += 1
			correct += 1
		elif request.POST.get(q.question) != q.currect_answer:
			wrong += 1
	obj = Result.objects.create(user_id=request.user,category = category,score=score,correct=correct,wrong=wrong)
	return redirect("app:dashboard")


def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("app:dashboard")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})


def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				if user.usertype == 1:
					return redirect("app:admin_dashboard")
				else:
					return redirect("app:dashboard")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})	


def logout_request(request):
	logout(request)
	return redirect("app:login")	


@login_required
def admin_dashboard(request):
	user = GeneralUser.objects.all()
	ques = Quiz.objects.all()
	res = Result.objects.all()
	cat = Category.objects.all()
	return render(request,'admin_dashboard.html',{'user':user,'ques':ques,'res':res,'cat':cat})


@login_required
def category_filter(request):
	if request.method == 'POST':
		id = request.POST.get('select_id')
		cat = Category.objects.get(id=id)
		qus = Quiz.objects.filter(category=cat)
		return render(request,'quiz.html',{'qus':qus,'cat':cat})
		

app/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>



<div class="container">

      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>


  <h2>Dynamic Tabs</h2>
  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Users</a></li>
    <li><a data-toggle="tab" href="#menu1">Questions</a></li>
    <li><a data-toggle="tab" href="#menu2">Answers</a></li>
    <li><a data-toggle="tab" href="#menu3">Result</a></li>
    <li><a data-toggle="tab" href="#menu4">Category</a></li>
  </ul>

  <div class="tab-content">
    <div id="home" class="tab-pane fade in active">
      <h3>Users</h3>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">full name</th>
      <th scope="col">phone</th>
      <th scope="col">email</th>
    </tr>
  </thead>
  {% for i in user %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{i.full_name}}</td>
      <td>{{i.phone}}</td>
      <td>{{i.email}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>
    </div>
    <div id="menu1" class="tab-pane fade">
      <h3>Menu 1</h3>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Question</th>

    </tr>
  </thead>
  {% for j in ques %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{j.question}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>
    </div>
    <div id="menu2" class="tab-pane fade">
      <h3>Answers</h3>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Question</th>
      <th scope="col">Answer</th>
    </tr>
  </thead>
  {% for j in ques %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{j.question}}</td>
      <td>{{j.currect_answer}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>
    </div>
    <div id="menu3" class="tab-pane fade">
      <h3>Result</h3>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"></th>
      <th scope="col">category</th>
      <th scope="col">score</th>
    </tr>
  </thead>
  {% for j in res %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{j.user_id}}</td>
      <td>{{j.category}}</td>
      <td>{{j.score}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>
    </div>
    <div id="menu4" class="tab-pane fade">
      <h3>Menu 3</h3>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">category</th>

    </tr>
  </thead>
  {% for j in cat %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{j.category_name}}</td>

    </tr>
  </tbody>
  {% endfor %}
</table>
    </div>
  </div>
</div>

</body>
</html>

app/templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"> </script>
	<title>Dashboard</title>
</head>
<body>

	<!-- <a href="{% url 'app:quiz' %}"><button type="button" class="btn btn-primary">Start quiz</button></a> -->


 {% if user.is_authenticated %}
      
  
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome, {{user.username}}</a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="/logout">Logout</a>
      </li>

      {% else %}

      <li class="nav-item">
        <a class="nav-link" href="/login">Login</a>
      </li>

      {% endif %}


<span>select category</span>

<form method="post" action="{% url 'app:category_filter' %}">
  {% csrf_token %}
<select name="select_id" id="select_id" class="form-select form-select-lg mb-3">
  {% for j in cat %}
  <option value="{{j.id}}">{{j.category_name}}</option>
  {% endfor %}  
</select>

<button type="submit" class="btn">Start Quiz</button>

</form>

<h2>Result</h2>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">category</th>
      <th scope="col">score</th>
      <th scope="col">correct</th>
      <th scope="col">wrong</th>
    </tr>
  </thead>
  {% for j in res %}
  <tbody>
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{j.category}}</td>
      <td>{{j.score}}</td>
      <td>{{j.correct}}</td>
      <td>{{j.wrong}}</td>
    </tr>
  </tbody>
  {% endfor %}
</table>

</body>
</html>


<!-- <script>
function val() {
    d = document.getElementById("select_id").value;
    $.ajax({
            type: 'post',
            data: {
                'id' : d,'csrfmiddlewaretoken': '{{ csrf_token }}'},
            url: "{% url 'app:category_filter' %}",
            success: function(data)
                    {
                  if (data['success'] == true){
                    alert("done");
                  }else{
                    alert("not");
                  }
            }
        });
}
</script> -->

app/templates/login.html
<div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

app/templates/quiz.html
<!DOCTYPE html>
<html>
<style type="text/css">
@import url('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css');
html,
body {
  height: 100%
}
</style>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<title>Dashboard</title>
</head>


<body>

<form method="post" action="{% url 'app:quiz' %}">	
	{% csrf_token %}

	<input type="text" name="category1" value="{{cat.id}}" hidden>

    {% for q in qus %}

<div class="form-group">
      <label for="question">{{q.question}}</label>
    </div>
    <div class="form-check">
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios1" value="{{q.option_1}}" checked>
            <label class="form-check-label" for="gridRadios1">
                {{q.option_1}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios2" value="{{q.option_2}}">
            <label class="form-check-label" for="gridRadios2">
                {{q.option_2}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios1" value="{{q.option_3}}">
            <label class="form-check-label" for="gridRadios1">
                {{q.option_3}}
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="{{q.question}}" id="gridRadios2" value="{{q.option_4}}">
            <label class="form-check-label" for="gridRadios2">
                {{q.option_4}}
            </label>
        </div>
        <br>
    </div>    

{% endfor %}

<button type="submit" class="btn btn-success">Submit</button>

</form>

</body>
</html>

app/templates/register.html
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form }}                    
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>